[package]
name = "form"
version = "0.3.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]
description = "A small script to move inline modules into the proper directory structure"
license = "MIT"
repository = "https://github.com/djmcgill/form"

[dependencies]
quote = "0.3"
getopts = "0.2"
log = "0.4.1"
env_logger = "0.5.1"
failure = "0.1.2"

[dependencies.syn]
version = "0.11.11"
features = ["full", "fold", "printing"]
